# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/xtwang/Google Drive/fvm_solver_euler2d"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/xtwang/Google Drive/fvm_solver_euler2d"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/xtwang/Google Drive/fvm_solver_euler2d/CMakeFiles" "/Users/xtwang/Google Drive/fvm_solver_euler2d/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/xtwang/Google Drive/fvm_solver_euler2d/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named solver.exe

# Build rule for target.
solver.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver.exe
.PHONY : solver.exe

# fast build rule for target.
solver.exe/fast:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/build
.PHONY : solver.exe/fast

src/ApplyBoundaryCondition.o: src/ApplyBoundaryCondition.cpp.o

.PHONY : src/ApplyBoundaryCondition.o

# target to build an object file
src/ApplyBoundaryCondition.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/ApplyBoundaryCondition.cpp.o
.PHONY : src/ApplyBoundaryCondition.cpp.o

src/ApplyBoundaryCondition.i: src/ApplyBoundaryCondition.cpp.i

.PHONY : src/ApplyBoundaryCondition.i

# target to preprocess a source file
src/ApplyBoundaryCondition.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/ApplyBoundaryCondition.cpp.i
.PHONY : src/ApplyBoundaryCondition.cpp.i

src/ApplyBoundaryCondition.s: src/ApplyBoundaryCondition.cpp.s

.PHONY : src/ApplyBoundaryCondition.s

# target to generate assembly for a file
src/ApplyBoundaryCondition.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/ApplyBoundaryCondition.cpp.s
.PHONY : src/ApplyBoundaryCondition.cpp.s

src/CalcGradient.o: src/CalcGradient.cpp.o

.PHONY : src/CalcGradient.o

# target to build an object file
src/CalcGradient.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcGradient.cpp.o
.PHONY : src/CalcGradient.cpp.o

src/CalcGradient.i: src/CalcGradient.cpp.i

.PHONY : src/CalcGradient.i

# target to preprocess a source file
src/CalcGradient.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcGradient.cpp.i
.PHONY : src/CalcGradient.cpp.i

src/CalcGradient.s: src/CalcGradient.cpp.s

.PHONY : src/CalcGradient.s

# target to generate assembly for a file
src/CalcGradient.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcGradient.cpp.s
.PHONY : src/CalcGradient.cpp.s

src/CalcNumericalFlux.o: src/CalcNumericalFlux.cpp.o

.PHONY : src/CalcNumericalFlux.o

# target to build an object file
src/CalcNumericalFlux.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcNumericalFlux.cpp.o
.PHONY : src/CalcNumericalFlux.cpp.o

src/CalcNumericalFlux.i: src/CalcNumericalFlux.cpp.i

.PHONY : src/CalcNumericalFlux.i

# target to preprocess a source file
src/CalcNumericalFlux.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcNumericalFlux.cpp.i
.PHONY : src/CalcNumericalFlux.cpp.i

src/CalcNumericalFlux.s: src/CalcNumericalFlux.cpp.s

.PHONY : src/CalcNumericalFlux.s

# target to generate assembly for a file
src/CalcNumericalFlux.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcNumericalFlux.cpp.s
.PHONY : src/CalcNumericalFlux.cpp.s

src/CalcResidual.o: src/CalcResidual.cpp.o

.PHONY : src/CalcResidual.o

# target to build an object file
src/CalcResidual.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcResidual.cpp.o
.PHONY : src/CalcResidual.cpp.o

src/CalcResidual.i: src/CalcResidual.cpp.i

.PHONY : src/CalcResidual.i

# target to preprocess a source file
src/CalcResidual.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcResidual.cpp.i
.PHONY : src/CalcResidual.cpp.i

src/CalcResidual.s: src/CalcResidual.cpp.s

.PHONY : src/CalcResidual.s

# target to generate assembly for a file
src/CalcResidual.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/CalcResidual.cpp.s
.PHONY : src/CalcResidual.cpp.s

src/Collective.o: src/Collective.cpp.o

.PHONY : src/Collective.o

# target to build an object file
src/Collective.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/Collective.cpp.o
.PHONY : src/Collective.cpp.o

src/Collective.i: src/Collective.cpp.i

.PHONY : src/Collective.i

# target to preprocess a source file
src/Collective.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/Collective.cpp.i
.PHONY : src/Collective.cpp.i

src/Collective.s: src/Collective.cpp.s

.PHONY : src/Collective.s

# target to generate assembly for a file
src/Collective.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/Collective.cpp.s
.PHONY : src/Collective.cpp.s

src/MainSolver.o: src/MainSolver.cpp.o

.PHONY : src/MainSolver.o

# target to build an object file
src/MainSolver.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/MainSolver.cpp.o
.PHONY : src/MainSolver.cpp.o

src/MainSolver.i: src/MainSolver.cpp.i

.PHONY : src/MainSolver.i

# target to preprocess a source file
src/MainSolver.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/MainSolver.cpp.i
.PHONY : src/MainSolver.cpp.i

src/MainSolver.s: src/MainSolver.cpp.s

.PHONY : src/MainSolver.s

# target to generate assembly for a file
src/MainSolver.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/MainSolver.cpp.s
.PHONY : src/MainSolver.cpp.s

src/TriMesh.o: src/TriMesh.cpp.o

.PHONY : src/TriMesh.o

# target to build an object file
src/TriMesh.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/TriMesh.cpp.o
.PHONY : src/TriMesh.cpp.o

src/TriMesh.i: src/TriMesh.cpp.i

.PHONY : src/TriMesh.i

# target to preprocess a source file
src/TriMesh.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/TriMesh.cpp.i
.PHONY : src/TriMesh.cpp.i

src/TriMesh.s: src/TriMesh.cpp.s

.PHONY : src/TriMesh.s

# target to generate assembly for a file
src/TriMesh.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/TriMesh.cpp.s
.PHONY : src/TriMesh.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/solver.exe.dir/build.make CMakeFiles/solver.exe.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... solver.exe"
	@echo "... src/ApplyBoundaryCondition.o"
	@echo "... src/ApplyBoundaryCondition.i"
	@echo "... src/ApplyBoundaryCondition.s"
	@echo "... src/CalcGradient.o"
	@echo "... src/CalcGradient.i"
	@echo "... src/CalcGradient.s"
	@echo "... src/CalcNumericalFlux.o"
	@echo "... src/CalcNumericalFlux.i"
	@echo "... src/CalcNumericalFlux.s"
	@echo "... src/CalcResidual.o"
	@echo "... src/CalcResidual.i"
	@echo "... src/CalcResidual.s"
	@echo "... src/Collective.o"
	@echo "... src/Collective.i"
	@echo "... src/Collective.s"
	@echo "... src/MainSolver.o"
	@echo "... src/MainSolver.i"
	@echo "... src/MainSolver.s"
	@echo "... src/TriMesh.o"
	@echo "... src/TriMesh.i"
	@echo "... src/TriMesh.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

